// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mfdfmQc3TFph-ZFQEkt07KYGz_SfMY8',
    appId: '1:340149721245:web:83b8f6ff93d75577749c74',
    messagingSenderId: '340149721245',
    projectId: 'demotivator-466e6',
    authDomain: 'demotivator-466e6.firebaseapp.com',
    storageBucket: 'demotivator-466e6.firebasestorage.app',
    measurementId: 'G-L2SSDT2J7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwdZrfqD9v9Yp0mj-rZJtpzC3mpnCpIY',
    appId: '1:340149721245:android:b1c13663bc9c4b9c749c74',
    messagingSenderId: '340149721245',
    projectId: 'demotivator-466e6',
    storageBucket: 'demotivator-466e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6NG4RD2tT-8efGafDxgO-3sdrJiVlhRM',
    appId: '1:340149721245:ios:6e3ca8a6a2208f00749c74',
    messagingSenderId: '340149721245',
    projectId: 'demotivator-466e6',
    storageBucket: 'demotivator-466e6.firebasestorage.app',
    iosBundleId: 'com.FrownFrames.WV17Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6NG4RD2tT-8efGafDxgO-3sdrJiVlhRM',
    appId: '1:340149721245:ios:387ad1998a5d680f749c74',
    messagingSenderId: '340149721245',
    projectId: 'demotivator-466e6',
    storageBucket: 'demotivator-466e6.firebasestorage.app',
    iosBundleId: 'com.example.newPaint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mfdfmQc3TFph-ZFQEkt07KYGz_SfMY8',
    appId: '1:340149721245:web:dd7f037909b0715b749c74',
    messagingSenderId: '340149721245',
    projectId: 'demotivator-466e6',
    authDomain: 'demotivator-466e6.firebaseapp.com',
    storageBucket: 'demotivator-466e6.firebasestorage.app',
    measurementId: 'G-NYRSRHEHGE',
  );
}
